PROGRAM ECTRANS_DEMONSTRATOR

USE PARKIND1, ONLY: JPRM, JPIM

IMPLICIT NONE

#include "setup_trans0.h"
#include "setup_trans.h"
#include "inv_trans.h"
#include "dir_trans.h"
#include "trans_inq.h"


INTEGER(KIND=JPIM), PARAMETER :: TRUNC=79
INTEGER(KIND=JPIM) :: NSPEC2, NGPTOT, M , N, I
REAL(KIND=JPRM), ALLOCATABLE, DIMENSION(:,:) :: SPECTRAL_FIELD
REAL(KIND=JPRM), ALLOCATABLE, DIMENSION(:,:,:) :: GRID_POINT_FIELD
INTEGER(KIND=JPIM), DIMENSION(0:TRUNC) :: SPECTRAL_INDICES


CALL SETUP_TRANS0(LDMPOFF=.TRUE.)

CALL SETUP_TRANS(KSMAX=TRUNC, KDGL=2 * (TRUNC + 1))

CALL TRANS_INQ(KSPEC2=NSPEC2, KGPTOT=NGPTOT)

PRINT*,NSPEC2, NGPTOT


ALLOCATE(SPECTRAL_FIELD(1,NSPEC2))
ALLOCATE(GRID_POINT_FIELD(NGPTOT,1,1))

CALL TRANS_INQ(KASM0=SPECTRAL_INDICES)

M = 3
N = 8

I = SPECTRAL_INDICES(M) + 2 * (N - M) + 1

SPECTRAL_FIELD(:,:) = 0.0
SPECTRAL_FIELD(1,I) = 1.0


CALL INV_TRANS(PSPSCALAR=SPECTRAL_FIELD, PGP=GRID_POINT_FIELD)

OPEN(7, FILE="grid_point_field.dat", FORM="UNFORMATTED")
WRITE(7) GRID_POINT_FIELD(:,1,1)
CLOSE(7)



END PROGRAM ECTRANS_DEMONSTRATOR

