#!/bin/bash


# ecmwf
if [ "$1" == "ecmwf" ]; then
	# gnu compiler
	#./launchTest -a ./arch/ecmwf/hpc2020/gnu/default 
	# intel compiler
	#./launchTest -a ./arch/ecmwf/hpc2020/default 
	# nvhpc + cuda on GPU
	./launchTest -a ./arch/ecmwf/hpc2020/nvhpc/gpu-cuda 
	# amd 
	#./launchTest -w -a ./arch/ecmwf/hpc2020/amd/afar/22.3.0/ 
fi





