#!/bin/bash

export testFolderName=testEctrans
testFolderAbsolutePath=$WORKDIR/${testFolderName}

function usage ()
{
    echo "Usage :  $0 [options] 
    -h|help             Display this message
    -w|without-cloning  Do not perform repositories cloning
    -a|arch             Path to use for compilation environment architecture"
}  

CLONEREPOSITORIES=1
ARCH=./arch/ecmwf/hpc2020/default

while getopts "a:hw" opt
do
    case $opt in

        h|help)  usage; exit 0   ;;
        w|without-cloning) CLONEREPOSITORIES=0;;
	a|arch) ARCH="$OPTARG";;
        *)  echo -e "Option does not exist : $OPTARG\n" >&2
            usage; exit 1   ;;

    esac    # --- end of case ---
done

if [ "$CLONEREPOSITORIES" -eq 1 ]; then

  # remove former temporary test folder
  if [ -d "${testFolderAbsolutePath}" ]; then
	echo "folder exists"
	rm -rf ${testFolderAbsolutePath}	
  fi

  mkdir ${testFolderAbsolutePath}

  #== get sources and put them on workdir

  # ecbuild on develop 
  git clone https://github.com/ecmwf/ecbuild.git ${testFolderAbsolutePath}/ecbuild

  # fiat on main
  git clone https://github.com/ecmwf-ifs/fiat.git ${testFolderAbsolutePath}/fiat

  # ectrans on develop
  git clone https://github.com/ecmwf-ifs/ectrans.git ${testFolderAbsolutePath}/ectrans

fi # $CLONEREPOSITORIES

#== Setting up the compilation environment

cp -r ./arch ${testFolderAbsolutePath}

#== Perform compilation and job on one node
#PARTITION=$(./findPartition)
#echo "launching compilation and testing with ${ARCH} architecture using ${PARTITION} partition"
#sbatch --partition=${PARTITION} compile.cjob ${testFolderName} ${ARCH} 
sbatch compile.cjob ${testFolderName} ${ARCH} 

