#!/bin/bash

function usage ()
{
    echo "Usage :  $0 [options] 
    -h|help             Display this message
    -w|without-cloning  Do not perform repositories cloning
    -a|arch             Path to use for compilation environment architecture
    -c|clonedir         Path to a folder to clone repositories default is \$WORKDIR if defined
    -i|install-fftw     Download and install fftw from repo"
}  

CLONEREPOSITORIES=1
INSTALLFFTW=0
export FFTW_ARCHIVE_NAME=fftw-3.3.10
ARCH=./arch/ecmwf/hpc2020/default

while getopts "a:c:hwi" opt
do
    case $opt in

        h|help)  usage; exit 0   ;;
        w|without-cloning) CLONEREPOSITORIES=0;;
	a|arch) ARCH="$OPTARG";;
	c|clonedir) export WORKDIR="$OPTARG";;
	i|install-fftw) INSTALLFFTW=1 ;;
        *)  echo -e "option error : $OPTARG\n" >&2
            usage; exit 1   ;;

    esac    # --- end of case ---
done

export testFolderName=testEctrans
testFolderAbsolutePath=$WORKDIR/${testFolderName}

if [ "$CLONEREPOSITORIES" -eq 1 ]; then

  # remove former temporary test folder
  if [ -d "${testFolderAbsolutePath}" ]; then
	echo "folder exists"
	rm -rf ${testFolderAbsolutePath}	
  fi

  mkdir ${testFolderAbsolutePath}

  #== get sources and put them on workdir

  # ecbuild on develop 
  git clone https://github.com/ecmwf/ecbuild.git ${testFolderAbsolutePath}/ecbuild

  # fiat on main
  git clone https://github.com/ecmwf-ifs/fiat.git ${testFolderAbsolutePath}/fiat

  # ectrans on develop
  git clone https://github.com/ecmwf-ifs/ectrans.git ${testFolderAbsolutePath}/ectrans


  # install fftw
  if [ "$INSTALLFFTW" -eq 1 ]; then
	  cd ${testFolderAbsolutePath} 
	  wget https://www.fftw.org/${FFTW_ARCHIVE_NAME}.tar.gz
	  tar -zvxf ${FFTW_ARCHIVE_NAME}.tar.gz
	  rm -f ${FFTW_ARCHIVE_NAME}.tar.gz
	  cd -
  fi

fi # $CLONEREPOSITORIES

#== Setting up the compilation environment

cp -r ./arch ${testFolderAbsolutePath}

#== Perform compilation and job on one node
PARTITION=$(./findPartition)
echo "launching compilation and testing with ${ARCH} architecture using ${PARTITION} partition"
#sbatch --partition=${PARTITION} compile.cjob ${testFolderName} ${ARCH} 
bash compile.cjob ${testFolderName} ${ARCH} 

